name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Correr tests Cypress
        run: npm run cy:run

      - name: Fusionar reportes
        if: always()
        run: npm run report:merge

      - name: Generar reporte HTML
        if: always()
        run: npm run report:generate

      - name: Subir reporte como artefacto
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reporte-mochawesome
          path: cypress/reports/report.html